ARG ELK_VERSION

# https://github.com/elastic/kibana-docker
FROM docker.io/ounismohamed/dockerelk_kibana:${ELK_VERSION}

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
