ARG ELK_VERSION

# https://github.com/elastic/elasticsearch-docker
FROM ounismohamed/elasticsearch:${ELK_VERSION}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
