ARG ELK_VERSION

# https://github.com/elastic/elasticsearch-docker
FROM docker.io/ounismohamed/dockerelk_elasticsearch:${ELK_VERSION}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
